export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const RETRIEVE_CATEGORY = 'RETRIEVE_CATEGORY';
export const RETRIEVE_CATEGORY_SUCCESS = 'RETRIEVE_CATEGORY_SUCCESS';
