export const CART_ID_KEY = 'CART_ID_KEY';

export const FETCH_CART_ID = 'FETCH_CART_ID';
export const FETCH_CART_ID_SUCCESS = 'FETCH_CART_ID_SUCCESS';

export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS';
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS';
export const FETCH_CART_PRODUCTS_FAILURE = 'FETCH_CART_PRODUCTS_FAILURE';
